name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: LaTeX
    - uses: xu-cheng/texlive-action@v2
      with:
          scheme: full

      - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you want to use
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rich
    # - name: Install TeX Live
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y texlive-full

    - name: Run tests
      run: |
        python tests/test.py
