name: Build

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test with Python 3.11
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx inspect --bootstrap
          docker buildx build --tag myimage --platform linux/amd64,linux/arm64 --load .
        working-directory: ./path/to/your/dockerfile/directory

      - name: Install rich library
        run: |
          docker run --rm myimage pip install rich

      - name: Run tests
        run: |
          docker run --rm myimage python tests/test.py