name: test pytemk

on:
  push:
    branches: [ main ]
  repository_dispatch:
      types: [manual-trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Use texlive-action
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk update
            apk add python3 py3-pip
            pip install rich
            python3 --version
            python3 tests/test.py
