name: Build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      texlive:
        image: latex-docker:latest
        options: --entrypoint "/bin/sh"
        ports:
          - 4000:4000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install rich library
      run: pip install rich

    - name: Run test.py
      run: python test.py