name: Test

on:
  # push: TODO 需要修改测试文件后再启用
  #   branches: [ main ]
  repository_dispatch:
      types: [manual-trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Use texlive-action
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            python3.11 -m venv venv3.11
            source venv3.11/bin/activate
            apk add py3-pip
            pip install --upgrade pip
            pip install rich build setuptools wheel pymupdf toml
            python3 --version
            make test
            make testwhl
            deactivate
